### ISSUE TITLE
Provável erro no gabarito da Prova 1B na questão 2) i) e 2) ii)

### ISSUE THREAD

**Issue by durvalcarvalho** [edsomjr/Compiladores#6]
Acredito que a resposta correta seja: **A e B** e não **A, B e L**, uma vez que não há produções de **L**.

Deste modo, na questão `2) ii)` o **L** é um terminal.

![image](https://user-images.githubusercontent.com/31013187/184028813-230ff4ab-daec-47c6-b094-cc57be376219.png)

Observação: Link do arquivo do gabarito: https://aprender3.unb.br/pluginfile.php/2233505/mod_resource/content/1/gabB.pdf

**Comment by edsomjr** [comment]
Durval,

O L surgiu por conta de um erro de digitação mesmo: no lugar dele era para ser um B. Pelas convenções de notação que apresentei na aula, L seria um não-terminal (maiúscula em itálico), mas na gramática não foi listada uma produção para ele.

Neste contexto, considerei para este item corretas as respostas 
1. A e B
2. A e L
3. A, B e L
